# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HeySunny' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HeySunny

  target 'HeySunnyTests' do
    inherit! :search_paths
    pod 'Charts'
    pod 'XCoordinator'
    # Pods for testing
  end

end
