# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HeySunny' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HeySunny
  pod 'Charts'
  pod 'XCoordinator'
  pod "UPCarouselFlowLayout"
  pod 'WeScan', '>= 0.9'
  pod 'Permission', '~> 3.1'
  pod 'Permission/Camera'
  pod 'M13Checkbox'
  pod 'TapCardScanner-iOS', '~> 1.0'


  target 'HeySunnyTests' do
    inherit! :search_paths

    pod 'XCoordinator'
    pod "UPCarouselFlowLayout"
    pod 'WeScan', '>= 0.9'
    pod 'Permission', '~> 3.1'
    pod 'Permission/Camera'
    pod 'TapCardScanner-iOS', '~> 1.0'
    # Pods for testing
  end

end
